#!/usr/bin/env python3
"""
Create GitHub Pull Request with automatic @claude and @codex review tags.

This script creates a PR and immediately posts a comment requesting AI review
from both @claude (GitHub Actions) and @codex (Codex Cloud, if configured).
"""

import subprocess
import sys
from pathlib import Path
from typing import Optional


def create_pr_with_ai_review(
    epic_id: str,
    title: str,
    body: str,
    base_branch: str = "main",
    draft: bool = False,
) -> Optional[str]:
    """
    Create PR with automatic AI review requests.

    Args:
        epic_id: Epic identifier (e.g., "EPIC-007")
        title: PR title
        body: PR description
        base_branch: Target branch (default: "main")
        draft: Create as draft PR (default: False)

    Returns:
        PR URL if successful, None if failed
    """
    try:
        # Step 1: Create PR using gh CLI
        cmd = [
            "gh", "pr", "create",
            "--title", title,
            "--body", body,
            "--base", base_branch,
        ]

        if draft:
            cmd.append("--draft")

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )

        pr_url = result.stdout.strip()
        print(f"✅ PR created: {pr_url}")

        # Step 2: Extract PR number from URL
        pr_number = pr_url.split("/")[-1]

        # Step 3: Post AI review request comment
        review_comment = f"""## 🤖 AI Review Requested

@claude Please review this PR for:
- Code quality and best practices
- Type safety and error handling
- Architecture compliance
- Security considerations

@codex review

---
*Epic: {epic_id}*
*Automated review request from tier1 workflow*
"""

        subprocess.run(
            ["gh", "pr", "comment", pr_number, "--body", review_comment],
            check=True,
            capture_output=True
        )

        print(f"✅ Posted AI review request to PR #{pr_number}")

        return pr_url

    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to create PR: {e}", file=sys.stderr)
        print(f"   stdout: {e.stdout}", file=sys.stderr)
        print(f"   stderr: {e.stderr}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"❌ Unexpected error: {e}", file=sys.stderr)
        return None


def create_feature_branch_and_pr(
    epic_id: str,
    epic_title: str,
    summary: str,
    base_branch: str = "main",
) -> Optional[dict]:
    """
    Create feature branch and PR for epic workflow.

    Args:
        epic_id: Epic identifier (e.g., "EPIC-007")
        epic_title: Epic title for branch naming
        summary: Implementation summary for PR body
        base_branch: Target branch (default: "main")

    Returns:
        Dict with branch name and PR URL, or None if failed
    """
    try:
        # Step 1: Generate branch name
        branch_slug = epic_title.lower()
        branch_slug = branch_slug.replace(" ", "-")
        branch_slug = "".join(c for c in branch_slug if c.isalnum() or c == "-")
        branch_name = f"feature/{epic_id.lower()}-{branch_slug}"

        # Step 2: Create and push feature branch
        subprocess.run(["git", "checkout", "-b", branch_name], check=True, capture_output=True)
        print(f"✅ Created branch: {branch_name}")

        subprocess.run(["git", "push", "-u", "origin", branch_name], check=True, capture_output=True)
        print(f"✅ Pushed branch to origin")

        # Step 3: Create PR with AI review
        pr_title = f"{epic_id}: {epic_title}"
        pr_body = f"""## Summary

{summary}

## Epic Details

- **Epic ID:** {epic_id}
- **Branch:** `{branch_name}`
- **Base:** `{base_branch}`

## Checklist

- [ ] Code quality verified
- [ ] Tests passing
- [ ] Documentation updated
- [ ] AI review addressed

---
*Generated by tier1 workflow `/execute-workflow`*
"""

        pr_url = create_pr_with_ai_review(
            epic_id=epic_id,
            title=pr_title,
            body=pr_body,
            base_branch=base_branch,
            draft=False
        )

        if pr_url:
            return {
                "branch": branch_name,
                "pr_url": pr_url,
                "pr_number": pr_url.split("/")[-1]
            }
        else:
            return None

    except subprocess.CalledProcessError as e:
        print(f"❌ Git operation failed: {e}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"❌ Unexpected error: {e}", file=sys.stderr)
        return None


if __name__ == "__main__":
    # CLI usage example
    if len(sys.argv) < 3:
        print("Usage: python pr_with_ai_review.py <epic-id> <title> [base-branch]")
        print("Example: python pr_with_ai_review.py EPIC-007 'Add semantic search' main")
        sys.exit(1)

    epic_id = sys.argv[1]
    title = sys.argv[2]
    base_branch = sys.argv[3] if len(sys.argv) > 3 else "main"

    body = f"""Implementation for {epic_id}

See epic specification in `.tasks/backlog/{epic_id}/`
"""

    pr_url = create_pr_with_ai_review(epic_id, title, body, base_branch)

    if pr_url:
        print(f"\n✅ Success! PR created with AI review: {pr_url}")
        sys.exit(0)
    else:
        print(f"\n❌ Failed to create PR")
        sys.exit(1)
